

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR

Spring:
  datasource:
    url:  jdbc:h2:file:./h2/test
    driver-class-name : org.h2.Driver
    username : sa
    password :
    platform : h2
  h2:
    console :
      enabled : true
  jpa:
    show-sql: true
  flyway:
    location : classpath/db/migration

Server :
  port : 8090